name: Staging Deployment
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - v*.*.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      function:
        description: 'Function name to be deploy'
        required: true
        default: 'hello-world'
      version:
        description: 'Version of function'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Parse Git Tag
        id: vars
        run: |
          echo "::set-output name=version::$(echo ${GITHUB_REF#refs/*/} | cut -d_ -f1)"
          echo "::set-output name=function::$(echo ${GITHUB_REF#refs/*/} | cut -d_ -f2)"

      - name: Apply Function Name
        run: |
          echo "THE_FUNCTION=${{ github.event.inputs.function || steps.vars.outputs.function }}" >> $GITHUB_ENV

      - name: Check output
        run: |
          echo "RELEASE_FUNCTION: ${{ github.event.inputs.function || steps.vars.outputs.function }}"
          echo "THE_FUNCTION: ${{ env.THE_FUNCTION }}"
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Build
        run: |-
          echo "THE_FUNCTION: ${{ env.THE_FUNCTION }}"
          npm install
          npm run build

