name: Staging Deployment
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - v*.*.*_*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      function:
        description: 'Function name to be deploy'
        required: true
        default: 'hello-world'
      version:
        description: 'Version of function'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          func=$(echo ${{steps.vars.outputs.tag}} | cut -d_ -f2)
          echo "::set-output name=function::$func"
      - name: Check output
        env:
          RELEASE_VERSION: "RELEASE_VERSION: ${{ steps.vars.outputs.tag }}" 
          RELEASE_FUNC: "RELEASE_FUNC: ${{ steps.vars.outputs.function }}" 
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ env.RELEASE_FUNC }}
