name: Staging Deployment
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    tags:
      - v*.*.*_*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      function:
        description: 'Function name to be deploy'
        required: true
        default: 'hello-world'
      version:
        description: 'Version of function'
        required: false

env:
  GCP_FUNCTION: ${{ github.event.inputs.function }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Parse Git Tag
        id: vars
        run: |
          ${{ steps.vars.outputs.function == 'main' || steps.vars.outputs.function == '' }}
          ${{ steps.vars.outputs.function }}

          echo "::set-output name=version::$(echo ${GITHUB_REF#refs/*/} | cut -d_ -f1)"
          echo "::set-output name=function::$(echo ${GITHUB_REF#refs/*/} | cut -d_ -f2)"
      - name: Set Version from Tag
        if: ${{ steps.vars.outputs.function == 'main' || steps.vars.outputs.function == '' }}
        run: echo ''
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.version }}
          GCP_FUNCTION: ${{ steps.vars.outputs.function }}
      - name: Check output
        run: |
          echo "RELEASE_VERSION: ${{ env.RELEASE_VERSION }}"
          echo "RELEASE_FUNCTION: ${{ env.GCP_FUNCTION }}"